# Generated by Django 2.2 on 2019-11-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_business_owner',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
