# Generated by Django 2.2.4 on 2019-09-10 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate_business',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='affiliate_business',
            name='legal_representative_lastname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='affiliate_business',
            name='legal_representative_name',
            field=models.CharField(max_length=255),
        ),
    ]
