# Generated by Django 2.2 on 2019-11-18 02:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191117_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancedetails',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
