# Generated by Django 2.2 on 2019-10-24 19:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191024_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepicture',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilepicture',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
