# Generated by Django 2.2 on 2019-11-18 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191117_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancedetails',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación'),
        ),
    ]
