# Generated by Django 2.2 on 2019-11-18 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_maintenancedetails_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancedetails',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='maintenancedetails',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Vehicle'),
        ),
    ]
