# Generated by Django 2.2 on 2019-10-27 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20191027_1743'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brand_Vehicle',
            new_name='Brand',
        ),
        migrations.RenameModel(
            old_name='Model_Vehicle',
            new_name='Model',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='brand_vehicle',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='model',
            old_name='brand_vehicle',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='model',
            old_name='model_vehicle',
            new_name='model',
        ),
    ]
